### ISSUE TITLE
No Sound in Output WAV File after Running Demo

### ISSUE THREAD

**Issue by xxnanyuan** [Ceaglex/LoVA#1]
Hi,

After downloading the provided checkpoint and running the demo, I noticed that the output WAV file has no sound. I have verified that all the logs appear to be the same as in your demonstration, and there are no obvious errors during the process.

I've noticed that all the values in the output tensor are 'NaN'.

Could you please help me troubleshoot this issue? Any guidance on possible reasons for the silent output would be much appreciated.

Thank you in advance!

**Comment by Ceaglex** [comment]
Hello! Thank you for your issue! This repo is only a first version, we will further improve the code. Could you please give me a screenshot of the output? Is there a message that some packages are missing?

**Comment by Ceaglex** [comment]
could you please check out if the  'flash_attn'   package is available ?
**from flash_attn import flash_attn_func, flash_attn_kvpacked_func**

**Comment by xxnanyuan** [comment]
![image](https://github.com/user-attachments/assets/73349ceb-abd7-40dc-b1be-d82e47723a2a)
The terminal output appears normal, and there are no errors. I’m having trouble locating the main inference block in your code. Could you please point me to its location?
The flash_attn package has been successfully set up.

**Comment by xxnanyuan** [comment]
Could you check if the demo works correctly in your environment?

**Comment by Ceaglex** [comment]
The inference code is the in the demo.ipynb. 
I will check if this is the issue of the environment or the uploaded weight. 
(By the way, I figure out some mistakes in the demo.ipynb, and i will fix it either)
![image](https://github.com/user-attachments/assets/0438075d-d64e-41f3-b066-62ccb502e6b4)

**Comment by Ceaglex** [comment]
The model weight from the baidu net also works well in my own environment.
Do you mind pulling the demo.ipynb file and run the code again? Or could your please paste your running code and i may help you to find the issue.

![image](https://github.com/user-attachments/assets/fa688e33-9ba3-4db6-b5fe-c455a5581dd1)

**Comment by Ceaglex** [comment]
I also add a "sample.py", you can run the code for inference to.
By the way, do you have the module "flash_attn_2_cuda"? Could you please run the following code?
**from flash_attn import flash_attn_func, flash_attn_kvpacked_func
import flash_attn_2_cuda**

**Comment by xxnanyuan** [comment]
Thank you for your quick response! The code I’m running is a concatenation of your demo.ipynb.

Could you kindly provide the MD5 checksum of the model using the following command?

```
md5sum epoch=60-step=2818.safetensors
82d7f6bb2604a0fcd0dc69bd67252f3a epoch=60-step=2818.safetensors
```

Additionally, I’d like to confirm if there are any pretrained models ckpt need to download besides ViT-L-14. If so, I’ll need to download them manually to the server.

Thank you!

**Comment by Ceaglex** [comment]
It seems that the model I use is different from yours. I download the model from baidu net and the md5 is different from yours.
![image](https://github.com/user-attachments/assets/0d7e19fb-be2b-4803-bdc6-fbab02ea4be3)
Maybe you can try to re-download the checkpoint? If the issue still exists, I will upload the weight again
LoVA's ckpt and CLIP are the only pretrained models you need. No more other models are required.

**Comment by xxnanyuan** [comment]
Thank you so much! I’ll try to download the ckpt again!

**Comment by xxnanyuan** [comment]
Everything is working well now. I sincerely apologize for the trouble caused. Thank you for your help!

**Comment by Ceaglex** [comment]
You're welcome!
